#!/usr/bin/env pwsh
# Generated by the `universalize-agents` skill. Windows only
# (see agent-setup.sh for macOS/Linux). Safe to re-run (idempotent).
# Project scope fills relative paths; global scope fills absolute paths.
# Creating symlinks on Windows requires Developer Mode or an elevated shell.

$ErrorActionPreference = 'Stop'

$AgentsDir = '.agents'

# __LINK_MAP__ contract: one "SRC_SUBDIR|DEST_DIR" line per (platform x type),
# where SRC_SUBDIR is skills|agents|commands and DEST_DIR matches the scope.
$LinkMap = @'
skills|.claude/skills
agents|.claude/agents
commands|.claude/commands
'@

function Write-AgentLog($message) { Write-Host "agent-setup: $message" }

# Relative paths (project scope) resolve from the repo root; this script lives
# at <root>\.agents\hooks\, so move two levels up. Absolute paths are untouched.
$IsRelative = -not [System.IO.Path]::IsPathRooted($AgentsDir)
if ($IsRelative) { Set-Location (Join-Path $PSScriptRoot '..\..') }

function Set-AgentLink($src, $dest) {
	if (Test-Path -LiteralPath $dest) {
		$existing = Get-Item -LiteralPath $dest -Force
		if ($existing.LinkType -eq 'SymbolicLink' -and $existing.Target -eq $src) {
			return
		}
		if ($existing.LinkType -ne 'SymbolicLink') {
			# Refuse to replace a real (non-symlink) path that a user may own.
			Write-AgentLog "SKIP (real path in the way): $dest"
			return
		}
		Remove-Item -LiteralPath $dest -Force
	}
	New-Item -ItemType SymbolicLink -Path $dest -Target $src | Out-Null
}

foreach ($line in $LinkMap -split "`r?`n") {
	$line = $line.Trim()
	if (-not $line) { continue }

	$sub, $destDir = $line -split '\|', 2
	if (-not $sub -or -not $destDir) { continue }

	$srcDir = Join-Path $AgentsDir $sub
	if (-not (Test-Path -LiteralPath $srcDir)) { continue }
	if (-not (Test-Path -LiteralPath $destDir)) {
		New-Item -ItemType Directory -Path $destDir -Force | Out-Null
	} else {
		# Clean up dangling symlinks in $destDir
		foreach ($link in Get-ChildItem -LiteralPath $destDir -Force) {
			if ($link.LinkType -eq 'SymbolicLink' -and -not (Test-Path -LiteralPath $link.FullName)) {
				Write-AgentLog "removing broken symlink: $($link.FullName)"
				Remove-Item -LiteralPath $link.FullName -Force
			}
		}
	}

	# Project scope only: keep the generated symlinks out of git via a single
	# .gitignore per platform base dir (the dest's parent), listing each
	# symlink subdir. The canonical content lives in (tracked) .agents/.
	if ($IsRelative) {
		$gi = Join-Path (Split-Path -Parent $destDir) '.gitignore'
		$entry = (Split-Path -Leaf $destDir) + '/'
		$lines = @()
		if (Test-Path -LiteralPath $gi) { $lines = @(Get-Content -LiteralPath $gi) }
		if ($lines -notcontains $entry) { Add-Content -LiteralPath $gi -Value $entry }
	}

	foreach ($item in Get-ChildItem -LiteralPath $srcDir -Force) {
		$dest = Join-Path $destDir $item.Name
		if ($IsRelative) {
			$target = [System.IO.Path]::GetRelativePath($destDir, (Join-Path $srcDir $item.Name))
		} else {
			$target = $item.FullName
		}
		Set-AgentLink $target $dest
	}
}

Write-AgentLog 'done.'
